Repository YAPP-Github/WeSpot-iOS, pull requests merged in 2024-06, with the labels that each got.

#4 feat: Tuist Monolithic Architecture 도입
  .DS_Store
  24th-App-Team-1-iOS/.gitignore
  24th-App-Team-1-iOS/.mise.toml
  24th-App-Team-1-iOS/App/Project.swift
  24th-App-Team-1-iOS/App/Resources/empty.txt
  24th-App-Team-1-iOS/App/Sources/empty.txt
  24th-App-Team-1-iOS/Core/Extensions/Project.swift
  24th-App-Team-1-iOS/Core/Extensions/Resources/empty.txt
  24th-App-Team-1-iOS/Core/Extensions/Sources/empty.txt
  24th-App-Team-1-iOS/Core/Networking/Project.swift
  24th-App-Team-1-iOS/Core/Networking/Resources/empty.txt
  24th-App-Team-1-iOS/Core/Networking/Sources/empty.txt
  24th-App-Team-1-iOS/Core/Storage/Project.swift
  24th-App-Team-1-iOS/Core/Storage/Resources/empty.txt
  24th-App-Team-1-iOS/Core/Storage/Sources/empty.txt
  24th-App-Team-1-iOS/Domain/HomeDomain/Project.swift
  24th-App-Team-1-iOS/Domain/HomeDomain/Resources/empty.txt
  24th-App-Team-1-iOS/Domain/HomeDomain/Sources/empty.txt
  24th-App-Team-1-iOS/Domain/ProfileDomain/Project.swift
  24th-App-Team-1-iOS/Domain/ProfileDomain/Resources/empty.txt
  24th-App-Team-1-iOS/Domain/ProfileDomain/Sources/empty.txt
  24th-App-Team-1-iOS/Feature/HomeFeature/Project.swift
  24th-App-Team-1-iOS/Feature/HomeFeature/Resources/empty.txt
  24th-App-Team-1-iOS/Feature/HomeFeature/Sources/empty.txt
  24th-App-Team-1-iOS/Feature/ProfileFeature/Project.swift
  24th-App-Team-1-iOS/Feature/ProfileFeature/Resources/empty.txt
  24th-App-Team-1-iOS/Feature/ProfileFeature/Sources/empty.txt
  24th-App-Team-1-iOS/Makefile
  24th-App-Team-1-iOS/Service/HomeService/Project.swift
  24th-App-Team-1-iOS/Service/HomeService/Resources/empty.txt
  24th-App-Team-1-iOS/Service/HomeService/Sources/empty.txt
  24th-App-Team-1-iOS/Service/ProfileService/Project.swift
  24th-App-Team-1-iOS/Service/ProfileService/Resources/empty.txt
  24th-App-Team-1-iOS/Service/ProfileService/Sources/empty.txt
  24th-App-Team-1-iOS/Shared/DesignSystem/Project.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/empty.txt
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/empty.txt
  24th-App-Team-1-iOS/Shared/ThirdPartyLib/Project.swift
  24th-App-Team-1-iOS/Shared/ThirdPartyLib/Resources/empty.txt
  24th-App-Team-1-iOS/Shared/ThirdPartyLib/Sources/empty.txt
  24th-App-Team-1-iOS/Tuist/Package.resolved
  24th-App-Team-1-iOS/Tuist/Package.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ModulePaths+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ResourceFileElements.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/SourceFilesList+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/Target+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/TargetDependency+Templates.swift
  24th-App-Team-1-iOS/Workspace.swift
Labels: ⚒️ SETTING, 도현🐶, 서우🐰

#6 feat: Xcode File Templates 도입
  .DS_Store
  24th-App-Team-1-iOS/Core/Util/Project.swift
  24th-App-Team-1-iOS/Core/Util/Sources/BaseViewController.swift
  24th-App-Team-1-iOS/Core/Util/Sources/empty.txt
  24th-App-Team-1-iOS/Feature/HomeFeature/Project.swift
  24th-App-Team-1-iOS/Feature/ProfileFeature/Project.swift
  24th-App-Team-1-iOS/Makefile
  24th-App-Team-1-iOS/Templates/feature.xctemplate/TemplateIcon-1016.png
  24th-App-Team-1-iOS/Templates/feature.xctemplate/TemplateInfo.plist
  24th-App-Team-1-iOS/Templates/feature.xctemplate/___FILEBASENAME___Feature.swift
  24th-App-Team-1-iOS/Templates/feature.xctemplate/___FILEBASENAME___Reactor.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ModulePaths+Templates.swift
Labels: ⚒️ SETTING, 서우🐰

#11 fix: Tuist ThirdPartyLib Module Undefined symbol issue 수정
  .DS_Store
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/Contents.json
  24th-App-Team-1-iOS/App/Resources/LaunchScreen.storyboard
  24th-App-Team-1-iOS/App/Resources/empty.txt
  24th-App-Team-1-iOS/App/Sources/Applications/AppDelegate.swift
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/empty.txt
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/Settings+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: 🐞 BUG, ⚒️ SETTING, 도현🐶

#12 feat: Common OSLog 모듈 추가
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/Core/Util/Sources/Logger/WSLogger.swift
Labels: ✨ FEATURE, 도현🐶
