Repository YAPP-Github/WeSpot-iOS, pull requests merged in 2024-08, with the labels that each got.

#77 feat: apple Login 로직 추가
  24th-App-Team-1-iOS/App/Sources/Applications/AppDelegate.swift
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DataDI/DataAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Login/SignInPresentationAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Login/SignUpPresntationAssembly.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/ASAuthorizationControllerProxy.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/AuthenticationServices+Rx.swift
  24th-App-Team-1-iOS/Core/Storage/Project.swift
  24th-App-Team-1-iOS/Core/Storage/Sources/APNsToken/APNsTokenManager.swift
  24th-App-Team-1-iOS/Core/Storage/Sources/UserDefaults/UserDefaultsManager.swift
  24th-App-Team-1-iOS/Core/Storage/Sources/UserDefaults/UserDefaultsWrapper.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/Entities/CreateRefreshTokenEntity.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/Entities/SchoolListEntity.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/Repositories/LoginRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/UseCases/CreateExistingMemberUseCase.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/UseCases/CreateNewMemberUseCase.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/UseCases/CreateProfanityCheckUseCase.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/UseCases/CreateRefreshTokenUseCase.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignInViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpClassViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpGenderViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpResultViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpSchoolViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignInViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpResultViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpSchoolViewController.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/DataMapping/CreateAccountResponseDTO.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/DataMapping/CreateProfanityCheckRequestDTO.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/DataMapping/CreateRefreshTokenResponseDTO.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/DataMapping/CreateSignUpTokenResponseDTO.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/DataMapping/SchoolListResponseDTO.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/Repository/LoginRepository.swift
  24th-App-Team-1-iOS/Tuist/Package.resolved
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/Entitlements+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ModulePaths+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: ✨ FEATURE, 서우🐰

#79 feat: 투표 완료 화면 API 연동
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Vote/VoteCompletePresentationAssembly.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/VoteEndPoint.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Entities/VoteAllEntity.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Repositories/VoteRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/UseCases/FetchAllVoteOptionsUseCase.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteAllCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteEmptyCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteHighCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteLowCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteAllCellReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteCompleteViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteEmptyCellReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteHighCellReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteLowCellReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Sections/VoteAllCompleteSection.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Sections/VoteCompleteSection.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Strings/String.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteCompleteViewController.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/DataMapping/VoteAllResponseDTO.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/Repository/VoteRepository.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_complete_broze_crwon_filed.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_complete_broze_crwon_filed.imageset/ic_complete_broze_crwon_filed.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_complete_gold_crown_filed.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_complete_gold_crown_filed.imageset/ic_vote_crown_filed.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_complete_silver_crown_filed.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_complete_silver_crown_filed.imageset/ic_complete_silver_crown_filed.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/img_empty_vote.filed.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/img_empty_vote.filed.imageset/img_empty_vote.filed.svg
Labels: ✨ FEATURE, 도현🐶

#81 feat: 투표 친구 등록 화면 추가
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Vote/VoteMainPresentationAssembly.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteCompleteViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteHomeViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteMainViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteProcessViewController.swift
Labels: ✨ FEATURE, 도현🐶

#82 feat: 로그인 진입화면 UI 수정 및 카카오 로그인 버튼에 API 로직 추가
  24th-App-Team-1-iOS/App/Sources/Applications/AppDelegate.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/Bundle+Extensions.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignInViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignInViewController.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/Repository/LoginRepository.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: ✨ FEATURE, 서우🐰

#90 feat: WSTabbarController 화면 연결
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
Labels: ✨ FEATURE, 도현🐶, 서우🐰

#85 feat: 회원가입 학교 검색 API 연동 및 로직 수정
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/LoginEndPoint.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/Entities/SchoolListEntity.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/Entities/SchoolListRequestQuery.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpSchoolViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Sections/SchoolSection.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpSchoolViewController.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/DataMapping/SchoolListRequestDTO.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/Repository/LoginRepository.swift
Labels: ✨ FEATURE, 서우🐰

#88 feat: 회원가입 이름 화면 비속어 API 연동
  24th-App-Team-1-iOS/App/Sources/DIContainer/DataDI/DataAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Login/SignUpPresntationAssembly.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/CommonEndPoint.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/LoginEndPoint.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Project.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/Entities/CreateCheckProfanityRequest.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/Repositories/CommonRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/UseCases/CreateCheckProfanityUseCase.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/Repositories/LoginRepositoryProtocol.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Project.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpNameViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpGenderViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpNameViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpResultViewController.swift
  24th-App-Team-1-iOS/Service/CommonService/Project.swift
  24th-App-Team-1-iOS/Service/CommonService/Sources/DataMapping/CreateCheckProfanityDTO.swift
  24th-App-Team-1-iOS/Service/CommonService/Sources/Repository/CommonRepository.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/DataMapping/CreateProfanityCheckRequestDTO.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/Repository/LoginRepository.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ModulePaths+Templates.swift
Labels: ✨ FEATURE, 서우🐰

#97 feat: 변경된 Tabbar Icon 수정
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/TabBar/ic_tabbar_message_selected.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/TabBar/ic_tabbar_message_selected.imageset/ic_tabbar_message_selected.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/TabBar/ic_tabbar_message_selected.imageset/icon-guide.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/TabBar/ic_tabbar_message_unselected.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/TabBar/ic_tabbar_message_unselected.imageset/ic_tabbar_message_unselected.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/TabBar/ic_tabbar_message_unselected.imageset/icon-guide.svg
Labels: ✨ FEATURE, 서우🐰

#92 fix: 회원가입 시, 전달 토큰 FcmToken 수정
  24th-App-Team-1-iOS/App/Project.swift
  24th-App-Team-1-iOS/App/Sources/Applications/AppDelegate.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/NotificationName+Extensions.swift
  24th-App-Team-1-iOS/Core/Storage/Sources/APNsToken/APNsTokenManager.swift
  24th-App-Team-1-iOS/Core/Storage/Sources/UserDefaults/UserDefaultsManager.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignInViewReactor.swift
  24th-App-Team-1-iOS/Tuist/Package.resolved
  24th-App-Team-1-iOS/Tuist/Package.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/Target+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/TargetDependency+Templates.swift
Labels: 🐞 BUG, 서우🐰

#95 feat: 프로필 이미지 설정 UI 구현 및 캐릭터 정보 API 연동
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Login/SetUpProfilePresntationAssembly.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/CommonEndPoint.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/Entities/FetchProfileBackgroundsEntity.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/Entities/FetchProfileImageEntity.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/Repositories/CommonRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/UseCases/FetchProfileBackgroundsUseCase.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/UseCases/FetchProfileImagesUseCase.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/UseCases/CreateProfanityCheckUseCase.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Cells/ProfileBackgroundColorCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Cells/ProfileCharacterImageViewCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Cells/SchoolSearchTableViewCell.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Components/ToggleProfileTableViewButton.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SetUpProfileImageViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Sections/ProfileSections.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SetUpProfileImageViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignInViewController.swift
  24th-App-Team-1-iOS/Service/CommonService/Sources/DataMapping/FetchProfileBackgroundsDTO.swift
  24th-App-Team-1-iOS/Service/CommonService/Sources/DataMapping/FetchProfileImagesDTO.swift
  24th-App-Team-1-iOS/Service/CommonService/Sources/Repository/CommonRepository.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_background_selected.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_background_selected.imageset/ic_profile_background_selected.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_background_unselected.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_background_unselected.imageset/ic_profile_background_unselected.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_character_selected.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_character_selected.imageset/ic_profile_character_selected.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_character_unselected.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_character_unselected.imageset/ic_profile_character_unselected.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_check.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_check.imageset/ic_profile_check.svg
Labels: ✨ FEATURE, 서우🐰

#100 feat: 쪽지 홈 카드 뷰 구현
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DataDI/DataAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Message/MessageMainPresentationAssembly.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/Date+Extensions.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/MessageEndPoint.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/UseCases/CreateExistingMemberUseCase.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/UseCases/CreateNewMemberUseCase.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/UseCases/CreateRefreshTokenUseCase.swift
  24th-App-Team-1-iOS/Domain/MessageDomain/Sources/Entities/FetchMessageRequest.swift
  24th-App-Team-1-iOS/Domain/MessageDomain/Sources/Entities/MessageStatusResponseEntity.swift
  24th-App-Team-1-iOS/Domain/MessageDomain/Sources/Entities/ReceivedMessageResponseEntity.swift
  24th-App-Team-1-iOS/Domain/MessageDomain/Sources/Entities/ReservedMessageResponseEntity.swift
  24th-App-Team-1-iOS/Domain/MessageDomain/Sources/Repositories/MessageRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/MessageDomain/Sources/UseCases/FetchMessagesStatusUseCase.swift
  24th-App-Team-1-iOS/Domain/MessageDomain/Sources/UseCases/FetchReceivedMessageUseCase.swift
  24th-App-Team-1-iOS/Domain/MessageDomain/Sources/UseCases/FetchReservedMessageUseCase.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Components/MessageCardView.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Reactors/MessageHomeViewReactor.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Reactors/MessagePageViewReactor.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/ViewControllers/MessageHomeViewController.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/ViewControllers/MessagePageViewController.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/ViewControllers/MessageReportViewController.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/ViewControllers/MessageStorageViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VotePageViewReactor.swift
  24th-App-Team-1-iOS/Service/MessageService/Sources/DataMapping/MessagesStatusResponseDTO.swift
  24th-App-Team-1-iOS/Service/MessageService/Sources/DataMapping/ReceievedMessageResponseDTO.swift
  24th-App-Team-1-iOS/Service/MessageService/Sources/DataMapping/ReservedMessageResponseDTO.swift
  24th-App-Team-1-iOS/Service/MessageService/Sources/Repository/MessageRepository.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/ic_ ellipsis.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/ic_ ellipsis.imageset/icn.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Message/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Message/ic_message_home_timer.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Message/ic_message_home_timer.imageset/ic_message_home_timer.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Message/img_message_home_letter_close.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Message/img_message_home_letter_close.imageset/Graphic2.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Message/img_message_home_letter_close.imageset/Graphic2@2x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Message/img_message_home_letter_close.imageset/Graphic2@3x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Message/img_message_home_letter_open.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Message/img_message_home_letter_open.imageset/Graphic.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Message/img_message_home_letter_open.imageset/Graphic@2x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Message/img_message_home_letter_open.imageset/Graphic@3x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Banner/WSBanner.swift
Labels: ✨ FEATURE, 서우🐰

#104 feat: 투표 인스타 공유하기 기능 추가
  24th-App-Team-1-iOS/Core/Extensions/Sources/UIView+Extensions.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/UIViewController+Extensions.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteCompleteViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteEffectViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteHomeViewController.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: ✨ FEATURE, 도현🐶

#107 feat: Message 신고 UI 구현
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Message/MessageExtraPresentationAssembly.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Cell/MessageReportTableViewCell.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Reactors/MessageReactiveExtensions.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Reactors/MessageReportViewReactor.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Sections/ReportMessageSection.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/ViewControllers/MessageReportViewController.swift
Labels: ✨ FEATURE, 서우🐰

#111 feat: 프로필 캐릭터 및 배경화면 변경 API 연동 및 UI 추가
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DataDI/DataAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/All/AllMainPresentationAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/All/AllMainProfileEditPresentationAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/All/AllMainProfilePresentationAssembly.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/ProfileEndPoint.swift
  24th-App-Team-1-iOS/Core/Util/Sources/GlobalState/WSGlobalStateService.swift
  24th-App-Team-1-iOS/Domain/AllDomain/Sources/Entities/UpdateUserProfileRequest.swift
  24th-App-Team-1-iOS/Domain/AllDomain/Sources/Entities/UserProfileEntity.swift
  24th-App-Team-1-iOS/Domain/AllDomain/Sources/Repositories/ProfileRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/AllDomain/Sources/UseCases/FetchUserProfileUseCase.swift
  24th-App-Team-1-iOS/Domain/AllDomain/Sources/UseCases/UpdateUserProfileUseCase.swift
  24th-App-Team-1-iOS/Domain/AllDomain/Sources/empty.txt
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/Entities/FetchProfileImageEntity.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Project.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Cell/MainTableViewHeaderFooterView.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Cell/ProfileBackgroundCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Cell/ProfileCharacterCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Reactors/AllMainViewReactor.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Reactors/ProfileBackgroundCellReactor.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Reactors/ProfileCharacterCellReactor.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Reactors/ProfileEditViewReactor.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Reactors/ProfileSettingViewReactor.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Sections/BackgroundEditSection.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Sections/CharacterEditSection.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/AllMainViewController.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/ProfileEditViewController.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/ProfileSettingViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SetUpProfileImageViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteAllCollectionViewCell.swift
  24th-App-Team-1-iOS/Service/AllService/Project.swift
  24th-App-Team-1-iOS/Service/AllService/Sources/DataMapping/UpdateUserProfileRequestDTO.swift
  24th-App-Team-1-iOS/Service/AllService/Sources/DataMapping/UserProfileResponseDTO.swift
  24th-App-Team-1-iOS/Service/AllService/Sources/Repository/ProfileRepository.swift
  24th-App-Team-1-iOS/Service/CommonService/Sources/DataMapping/FetchProfileImagesDTO.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Button/WSToggleProfileTableViewButton.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/TextField/WSTextField.swift
  24th-App-Team-1-iOS/Shared/ThirdPartyLib/Project.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ModulePaths+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/TargetDependency+Templates.swift
Labels: ✨ FEATURE, 도현🐶

#94 feat: 회원가입 정보 수정 및 뒤로가기 로직 구현
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Login/SignInPresentationAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Login/SignUpPresntationAssembly.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/NotificationName+Extensions.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/LoginEndPoint.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/Entities/CreateAccountRequest.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Components/PolicyAgreementBottomSheetView.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Components/SelectPolicyAgreementView.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignInViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpClassViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpGenderViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpGradeViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpNameViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpResultViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpSchoolViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignInViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpClassViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpGenderViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpGradeViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpNameViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpResultViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpSchoolViewController.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/DataMapping/CreateAccountRequestDTO.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/Repository/LoginRepository.swift
Labels: ✨ FEATURE, 서우🐰

#114 feat: TestFlight 배포를 위한 작업 병합 및 오류 수정
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/All/AllMainProfilePresentationAssembly.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Cells/ProfileCharacterImageViewCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Reactors/MessagePageViewReactor.swift
  24th-App-Team-1-iOS/Tuist/Package.resolved
  24th-App-Team-1-iOS/Tuist/Package.swift
Labels: ✨ FEATURE, 도현🐶, 서우🐰

#117 feat: KeyChain Swift 도입
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/Core/Storage/Sources/Keychain/KeychainManager.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignInViewReactor.swift
  24th-App-Team-1-iOS/Shared/ThirdPartyLib/Project.swift
  24th-App-Team-1-iOS/Tuist/Package.resolved
  24th-App-Team-1-iOS/Tuist/Package.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/TargetDependency+Templates.swift
Labels: ✨ FEATURE, 서우🐰

#121 fix: Custom Tabbar 선택된 탭 텍스트 글자색 처리
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/TabBar/WSTabBarButton.swift
Labels: 🐞 BUG, 서우🐰

#124 feat: 유저 탈퇴 API 로직 추가
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/All/AllMainProfileResignPresentationAssembly.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/ProfileEndPoint.swift
  24th-App-Team-1-iOS/Domain/AllDomain/Sources/Repositories/ProfileRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/AllDomain/Sources/UseCases/CreateUserResignUseCase.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Cell/MainTableViewCell.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Reactors/ProfileEditViewReactor.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/Reactors/ProfileResignViewReactor.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/AllMainViewController.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/ProfileAccountSettingViewController.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/ProfileEditViewController.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/ProfileResignNoteViewController.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/ProfileResignViewController.swift
  24th-App-Team-1-iOS/Service/AllService/Sources/Repository/ProfileRepository.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/NavigationBar/ic_navigationBar_setting_filed.imageset/ic_navigationBar_setting_filed.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_arrow_filed.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_arrow_filed.imageset/ic_profile_arrow_filed.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_vote_filed.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_vote_filed.imageset/ic_profile_vote_filed 1.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_vote_filed.imageset/ic_profile_vote_filed 2.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/ic_profile_vote_filed.imageset/ic_profile_vote_filed.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/NavigationBar/WSNavigationBar.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/NavigationBar/WSNavigationConstraintProperty.swift
  24th-App-Team-1-iOS/Tuist/Package.swift
Labels: ✨ FEATURE, 도현🐶

#127 feat: 알림 UI 및 API 기능 구현
  24th-App-Team-1-iOS/App/Project.swift
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DataDI/DataAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Notification/NotificationPresentationAssembly.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/NotificationName+Extensions.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/UIViewController+Extensions.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/NotificationEndPoint.swift
  24th-App-Team-1-iOS/Domain/NotificationDomain/Project.swift
  24th-App-Team-1-iOS/Domain/NotificationDomain/Sources/Entities/NotificationEntity.swift
  24th-App-Team-1-iOS/Domain/NotificationDomain/Sources/Entities/NotificationReqeustQuery.swift
  24th-App-Team-1-iOS/Domain/NotificationDomain/Sources/Repositories/NotificationRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/NotificationDomain/Sources/UseCases/FetchUserNotificationItemUseCase.swift
  24th-App-Team-1-iOS/Domain/NotificationDomain/Sources/UseCases/UpdateUserNotificationItemUseCase.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/AllMainViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignInViewReactor.swift
  24th-App-Team-1-iOS/Feature/NotificationFeature/Project.swift
  24th-App-Team-1-iOS/Feature/NotificationFeature/Sources/Presentation/Cell/NotificationTableViewCell.swift
  24th-App-Team-1-iOS/Feature/NotificationFeature/Sources/Presentation/Reactors/NotificationCellReactor.swift
  24th-App-Team-1-iOS/Feature/NotificationFeature/Sources/Presentation/Reactors/NotificationViewReactor.swift
  24th-App-Team-1-iOS/Feature/NotificationFeature/Sources/Presentation/Sections/NotificationSection.swift
  24th-App-Team-1-iOS/Feature/NotificationFeature/Sources/Presentation/ViewControllers/NotificationViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteAllCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteHighCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteCompleteViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteMainViewController.swift
  24th-App-Team-1-iOS/Service/NotificationService/Project.swift
  24th-App-Team-1-iOS/Service/NotificationService/Sources/DataMapping/NotificationRequestDTO.swift
  24th-App-Team-1-iOS/Service/NotificationService/Sources/DataMapping/NotificationResponseDTO.swift
  24th-App-Team-1-iOS/Service/NotificationService/Sources/Repository/NotificationRepository.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Notification/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Notification/ic_notification_alarm_filed.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Notification/ic_notification_alarm_filed.imageset/ic_notification_alarm_filed.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/bg_result_gradation.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/bg_result_gradation.imageset/background.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/bg_result_gradation.imageset/bg_result_gradation 1.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/bg_result_gradation.imageset/bg_result_gradation 2.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/bg_result_gradation.imageset/bg_result_gradation.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/bg_result_gradation.imageset/vote_background.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/bg_result_gradation.imageset/vote_image.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_vote_analyze.imageset/ic_vote_analyze 1.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_vote_analyze.imageset/ic_vote_analyze 2.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_vote_analyze.imageset/ic_vote_analyze.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/NavigationBar/WSNavigationBar.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/NavigationBar/WSNavigationConstraintProperty.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ModulePaths+Templates.swift
Labels: ✨ FEATURE, 도현🐶

#131 feat: 알림 화면 화면 전환 로직 추가 및 일부 QA 반영
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Vote/VoteMainPresentationAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Vote/VotePresentationAssembly.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/Date+Extensions.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/NotificationName+Extensions.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/UIViewController+Extensions.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/WSURLItemSource.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/VoteEndPoint.swift
  24th-App-Team-1-iOS/Core/Util/Sources/GlobalState/WSGlobalStateService.swift
  24th-App-Team-1-iOS/Domain/NotificationDomain/Sources/Entities/NotificationEntity.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Entities/VoteClassMatesEntity.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Repositories/VoteRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/UseCases/FetchClassMatesUseCase.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/ProfileAccountSettingViewController.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/ProfileResignNoteViewController.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/ProfileResignViewController.swift
  24th-App-Team-1-iOS/Feature/AllFeature/Sources/Presentation/ViewControllers/ProfileUserBlockViewController.swift
  24th-App-Team-1-iOS/Feature/NotificationFeature/Sources/Presentation/Reactors/NotificationViewReactor.swift
  24th-App-Team-1-iOS/Feature/NotificationFeature/Sources/Presentation/ViewControllers/NotificationViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteInventoryHeaderFooterView.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteCompleteViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteHomeViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteMainViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteProcessViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteBeginViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteCompleteViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteInventoryViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteMainViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteProcessViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteResultViewController.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/DataMapping/VoteClassMateResponseDTO.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/Repository/VoteRepository.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/img_profile_resign_filed.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/img_profile_resign_filed.imageset/img_profile_resign_filed 1.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/img_profile_resign_filed.imageset/img_profile_resign_filed 2.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Profile/img_profile_resign_filed.imageset/img_profile_resign_filed.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Alert/WSAlertBuilder.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Alert/WSAlertView.swift
Labels: ✨ FEATURE, 도현🐶

#122 feat: 토큰 재발급 API 추가
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/CommonEndPoint.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/ServiceImpl/WSNetworkInterceptor.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/ServiceImpl/WSNetworkService.swift
  24th-App-Team-1-iOS/Core/Storage/Sources/RefreshTokenManager.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/Entities/CreateAccountEntity.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/Entities/CreateRefreshTokenRequest.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/Repositories/LoginRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/UseCases/CreateRefreshTokenUseCase.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignInViewReactor.swift
  24th-App-Team-1-iOS/Service/CommonService/Sources/DataMapping/CreateCommonAccountResponseDTO.swift
  24th-App-Team-1-iOS/Service/CommonService/Sources/DataMapping/CreateRefreshTokenRequestDTO.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/Repository/LoginRepository.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: ✨ FEATURE, 서우🐰

#133 feat: Alamofire interceptor WSNetwork 모듈 내부 구현
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/Core/Networking/Project.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/CommonEndPoint.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/ReissueEndPoint.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/ServiceImpl/WSNetworkInterceptor.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/ServiceImpl/WSNetworkService.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/TokenManager/TokenStorage/ReissueToken.swift
  24th-App-Team-1-iOS/Core/Storage/Sources/RefreshTokenManager.swift
  24th-App-Team-1-iOS/Domain/CommonDomain/Sources/Entities/CreateRefreshTokenRequest.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteProcessViewController.swift
  24th-App-Team-1-iOS/Service/CommonService/Sources/DataMapping/CreateRefreshTokenRequestDTO.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ModulePaths+Templates.swift
Labels: ✨ FEATURE, 도현🐶
