Repository YAPP-Github/WeSpot-iOS, pull requests merged in 2024-07, with the labels that each got.

#19 feat: DesignSystem Module WSTextfield 컴포넌트 추가
  24th-App-Team-1-iOS/Core/Extensions/Sources/UIViewController+Extensions.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/lock.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/lock.imageset/lock.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/magnifyingglass.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/magnifyingglass.imageset/magnifyingglass.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/TextField/WSTextField.swift
Labels: ✨ FEATURE, 서우🐰

#20 feat: DesignSystem Module Banner 컴포넌트 추가
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/Letter.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/Letter.imageset/Frame 427323014.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/Letter.imageset/Frame 427323014@2x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/Letter.imageset/Frame 427323014@3x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/Timer.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/Timer.imageset/Group 482199.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/Timer.imageset/Group 482199@2x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/Timer.imageset/Group 482199@3x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/add.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/add.imageset/Frame 427323014.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/arrow_right.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/arrow_right.imageset/icn.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/invite.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/invite.imageset/Frame 427323014.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/message.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/message.imageset/Frame 427323014.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/reservation.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/reservation.imageset/Frame 427323014.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/voting.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/BannerIcon/voting.imageset/Frame 427323014.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Banner/WSBanner+Extensions.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Banner/WSBanner.swift
Labels: ✨ FEATURE, 서우🐰

#28 feat: Body11 추가 및 Body10 수정
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Font/WSFont.swift
Labels: ✨ FEATURE, 서우🐰

#25 feat: DesignSystem Module WSButton 컴포넌트 추가
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Button/WSButton.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Button/WSButtonColor.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Button/WSButtonProperty.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Button/WSButtonType.swift
Labels: ✨ FEATURE, 도현🐶

#26 feat: WSToast 구현 및 Extension 추가, WSToast icon assets 추가
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/checkmark.fill.positive.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/checkmark.fill.positive.imageset/checkmark.circle.fill.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/exclamationmark.fill.destructive.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/exclamationmark.fill.destructive.imageset/exclamationmark.circle.fill.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/icn.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/icn.imageset/icn.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/icn.imageset/icn@2x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/icn.imageset/icn@3x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Toast/WSToast+Extensions.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Toast/WSToast.swift
Labels: ✨ FEATURE, 서우🐰

#31 feat: DesignSystem Module WSAlert 컴포넌트 추가
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Alert/WSAlertActionProperty.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Alert/WSAlertActionType.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Alert/WSAlertBuilder.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Alert/WSAlertView.swift
Labels: ✨ FEATURE, 도현🐶

#42 fix: Template 파일 생성 명 변경
  24th-App-Team-1-iOS/Makefile
  24th-App-Team-1-iOS/Templates/feature.xctemplate/___FILEBASENAME___ViewController.swift
  24th-App-Team-1-iOS/Templates/feature.xctemplate/___FILEBASENAME___ViewReactor.swift
Labels: ⚒️ SETTING, 서우🐰

#36 feat: NSAttributedString+Extensions 생성 및 attributedText 함수 추가
  24th-App-Team-1-iOS/Core/Extensions/Sources/NSAttributedString+Extensions.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Label/WSLabel.swift
Labels: ✨ FEATURE, 서우🐰

#39 feat: AppIcon 추가
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/1024x1024px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/114x114px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/120x120px 1.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/120x120px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/128x128px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/136x136px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/152x152px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/167x167px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/180x180px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/192x192.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/40x40px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/58x58px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/60x60px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/76x76px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/80x80px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/87x87px.png
  24th-App-Team-1-iOS/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/AppIcon/AppIcon.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/AppIcon/AppIcon.imageset/Group 482080.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/AppIcon/AppIcon.imageset/Group 482080@2x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/AppIcon/AppIcon.imageset/Group 482080@3x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/AppIcon/AppIcon_Large.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/AppIcon/AppIcon_Large.imageset/Group 482146.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/AppIcon/AppIcon_Large.imageset/Group 482146@2x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/AppIcon/AppIcon_Large.imageset/Group 482146@3x.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/AppIcon/Contents.json
Labels: ✨ FEATURE, 서우🐰

#40 feat: 투표 메인 UI 및 기능 작업
  24th-App-Team-1-iOS/App/Project.swift
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/VoteDIContainer.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/Date+Extensions.swift
  24th-App-Team-1-iOS/Core/Util/Sources/BaseViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Project.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Components/VoteToggleView.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteMainViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteMainViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteResultViewController.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/NavigationBar/notice.imageset/notice.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_symbol.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_symbol.imageset/vote_symbol 1.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_symbol.imageset/vote_symbol 2.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_symbol.imageset/vote_symbol.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Banner/WSBanner.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ModulePaths+Templates.swift
Labels: ✨ FEATURE, 도현🐶

#44 feat: Login Feature 생성 및 UI 구현
  24th-App-Team-1-iOS/App/Project.swift
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Project.swift
  24th-App-Team-1-iOS/Domain/LoginDomain/Resources/empty.txt
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/empty.txt
  24th-App-Team-1-iOS/Feature/LoginFeature/Project.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Resources/empty.txt
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Components/ConfirmInfoBottomSheetView.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Components/GenderCardButton.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Components/GradientView.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Components/PolicyAgreementBottomSheetView.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Components/SchoolSearchTableViewCell.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Components/SelectGradeBottomSheetView.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Components/SelectGradeView.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Components/SelectPolicyAgreementView.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignInViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpClassViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpCompleteViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpGenderViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpGradeViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpNameViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpResultViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/Reactors/SignUpSchoolViewReactor.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignInViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpClassViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpCompleteViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpGenderViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpGradeViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpNameViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpResultViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/Presentation/ViewControllers/SignUpSchoolViewController.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Sources/empty.txt
  24th-App-Team-1-iOS/Service/LoginService/Project.swift
  24th-App-Team-1-iOS/Service/LoginService/Resources/empty.txt
  24th-App-Team-1-iOS/Service/LoginService/Sources/empty.txt
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/GenderIcon/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/GenderIcon/boy.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/GenderIcon/boy.imageset/img.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/GenderIcon/girl.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/GenderIcon/girl.imageset/img.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/check.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/check.imageset/Exclude.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/check_Selected.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/check_Selected.imageset/Exclude.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/profile.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Icons/profile.imageset/프로필.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Login/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Login/appleLoginButton.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Login/appleLoginButton.imageset/Social Login.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Login/kakaoLoginButton.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Login/kakaoLoginButton.imageset/Social Login.svg
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ModulePaths+Templates.swift
Labels: ✨ FEATURE, 서우🐰

#46 feat: 투표 결과 UI 및 기능 구현
  24th-App-Team-1-iOS/Core/Extensions/Sources/UIPageViewController+Extensions.swift
  24th-App-Team-1-iOS/Core/Util/Sources/GlobalState/WSGlobalStateService.swift
  24th-App-Team-1-iOS/Core/Util/Sources/GlobalTypes/VoteTypes.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Project.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteResultCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Components/VoteRankView.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Components/VoteToggleView.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteHomeViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteMainViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VotePageViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteResultViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Sections/VoteResultSection.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Strings/String.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteHomeViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteMainViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VotePageViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteResultViewController.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_background.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_background.imageset/background.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_background.imageset/vote_background.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_background.imageset/vote_image.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_background_cell.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_background_cell.imageset/image.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_character.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_character.imageset/vote_character.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_crwon.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_crwon.imageset/icn.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Button/WSButton.swift
Labels: ✨ FEATURE, 도현🐶

#50 feat: 투표 시작 UI 및 기능 구현
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/Core/Util/Sources/BaseViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteBeginViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteBeginViewController.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Project.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Lotties/demo.lottie
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Lottie/WSLottieView.swift
  24th-App-Team-1-iOS/Shared/ThirdPartyLib/Project.swift
  24th-App-Team-1-iOS/Tuist/Package.resolved
  24th-App-Team-1-iOS/Tuist/Package.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/TargetDependency+Templates.swift
  24th-App-Team-1-iOS/Tuist/ResourceSynthesizers/lottie.stencil
Labels: ✨ FEATURE, 도현🐶

#54 feat: 예약된 쪽지뷰 UI 구현
  24th-App-Team-1-iOS/App/Project.swift
  24th-App-Team-1-iOS/Core/Util/Sources/GlobalNotification/WSGlobalNotification.swift
  24th-App-Team-1-iOS/Domain/MessageDomain/Resources/empty.txt
  24th-App-Team-1-iOS/Domain/MessageDomain/Sources/empty.txt
  24th-App-Team-1-iOS/Domain/MessageDomain/project.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Resources/empty.txt
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Cell/ReservedMessageTableViewCell.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Reactors/ReservedMessageViewReactor.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Sections/ReservedMessageSection.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/ViewControllers/ReservedMessageViewController.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/empty.txt
  24th-App-Team-1-iOS/Feature/MessageFeature/project.swift
  24th-App-Team-1-iOS/Service/MessageService/Resources/empty.txt
  24th-App-Team-1-iOS/Service/MessageService/Sources/empty.txt
  24th-App-Team-1-iOS/Service/MessageService/project.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ModulePaths+Templates.swift
Labels: ✨ FEATURE, 서우🐰

#56 feat: WSNetwork Vote API Router 추가 및 DIContainer 구현
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DataDI/DataAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Vote/VotePresentationAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/VoteDIContainer.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/Reactive+Extensions.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/VoteEndPoint.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/ServiceImpl/WSNetworkService.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Protocol/EndPointProtocol/WSNetworkEndPoint.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Protocol/ServiceProtocol/WSNetworkServiceProtocol.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Utils/WSRequestParameters.swift
  24th-App-Team-1-iOS/Core/Util/Sources/Dependency/DependencyInjector.swift
  24th-App-Team-1-iOS/Core/Util/Sources/Extensions/WSLogger+Extensions.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Project.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Entities/VoteOptionEntity.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Repositories/VoteRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/UseCases/FetchVoteOptionsUseCase.swift
  24th-App-Team-1-iOS/Feature/MessageFeature/Sources/Presentation/Sections/ReservedMessageSection.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Project.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteMainViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteMainViewController.swift
  24th-App-Team-1-iOS/Service/VoteService/Project.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/DataMapping/VoteOptionResponseDTO.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/Repository/VoteRepository.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/ModulePaths+Templates.swift
Labels: ✨ FEATURE, 도현🐶

#59 feat: WSButton AttributedString 적용 코드 추가
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Alert/WSAlertView.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Button/WSButton.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Button/WSButtonType.swift
Labels: ✨ FEATURE, 도현🐶

#62 fix: lineHeigth 값 1.26 조정 및 중복되는 함수 제거
  24th-App-Team-1-iOS/Core/Extensions/Sources/NSAttributedString+Extensions.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Font/WSFont.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/TextField/WSTextField.swift
Labels: 🐞 BUG, 서우🐰

#63 feat: 투표 진행 UI 및 기능 구현
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Vote/VoteMainPresentationAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Vote/VotePresentationAssembly.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/NotificationName+Extensions.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/Reactive+Extensions.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/UIColor+Extensions.swift
  24th-App-Team-1-iOS/Core/Networking/Project.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/VoteEndPoint.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Utils/WSObservable+Extensions.swift
  24th-App-Team-1-iOS/Core/Util/Project.swift
  24th-App-Team-1-iOS/Core/Util/Sources/BaseViewController.swift
  24th-App-Team-1-iOS/Core/Util/Sources/Dependency/DependencyContainer.swift
  24th-App-Team-1-iOS/Core/Util/Sources/Dependency/DependencyInjector.swift
  24th-App-Team-1-iOS/Core/Util/Sources/GlobalState/WSGlobalStateService.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Entities/CreateVoteEntity.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Entities/CreateVoteReqeuest.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Repositories/VoteRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/UseCases/CreateVoteUseCase.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteProcessTableViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteHomeViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteMainViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VotePageViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteProcessCellReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteProcessViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteResultViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Sections/VoteProcessSection.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Sections/VoteResultSection.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Strings/String.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteBeginViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteHomeViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteMainViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VotePageViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteProcessViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteResultViewController.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/DataMapping/CreateVoteRequestDTO.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/DataMapping/CreateVoteResponseDTO.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/Repository/VoteRepository.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Common/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Common/ic_common_profile427323024.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Common/ic_common_profile427323024.imageset/ic_common_profile427323024 1.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Common/ic_common_profile427323024.imageset/ic_common_profile427323024 2.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Common/ic_common_profile427323024.imageset/ic_common_profile427323024.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/NavigationBar/WSNavigationBar.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/NavigationBar/WSNavigationTypeProperty.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/TabBar/WSTabBarViewController.swift
Labels: ✨ FEATURE, 도현🐶

#64 feat: 투표 결과 화면 API 연동 로직 추가
  24th-App-Team-1-iOS/App/Sources/DIContainer/DoaminDI/DomainAssembly.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Vote/VoteMainPresentationAssembly.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/NSAttributedString+Extensions.swift
  24th-App-Team-1-iOS/Core/Networking/Sources/Implement/implementation/EndPointImpl/VoteEndPoint.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Entities/VoteWinnerEntity.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Entities/VoteWinnerRequestQuery.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/Repositories/VoteRepositoryProtocol.swift
  24th-App-Team-1-iOS/Domain/VoteDomain/Sources/UseCases/FetchWinnerVoteOptionsUseCase.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteResultCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteMainViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteResultCellReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteResultViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Sections/VoteResultSection.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteMainViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VotePageViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteResultViewController.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/DataMapping/VoteWinnerRequestDTO.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/DataMapping/VoteWinnerResponseDTO.swift
  24th-App-Team-1-iOS/Service/VoteService/Sources/Repository/VoteRepository.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_vote_analyze.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_vote_analyze.imageset/ic_vote_analyze 1.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_vote_analyze.imageset/ic_vote_analyze 2.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_vote_analyze.imageset/ic_vote_analyze.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/Button/WSButton.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Sources/Components/TextField/WSTextField.swift
Labels: ✨ FEATURE, 도현🐶

#69 feat: 투표 완료 화면 UI 작업
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/App/Sources/DIContainer/PresentationDI/Vote/VoteCompletePresentationAssembly.swift
  24th-App-Team-1-iOS/Core/Extensions/Sources/UIView+Extensions.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteAllCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteHighCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteLowCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Cell/VoteResultCollectionViewCell.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Components/VoteCompleteLandingView.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Components/VoteCompleteOnBoardingView.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteAllCellReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Reactors/VoteCompleteViewReactor.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Sections/VoteAllCompleteSection.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Sections/VoteCompleteSection.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/Strings/String.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteCompleteViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteHomeViewController.swift
  24th-App-Team-1-iOS/Feature/VoteFeature/Sources/Presentation/ViewControllers/VoteResultViewController.swift
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/bg_result_gradation.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/bg_result_gradation.imageset/background.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/bg_result_gradation.imageset/vote_background.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/bg_result_gradation.imageset/vote_image.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_complete_crown_filed.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_complete_crown_filed.imageset/ic_vote_crown_filed.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_complete_share_outline.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_complete_share_outline.imageset/ic_share_outline.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_result_crwon_filed.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/ic_result_crwon_filed.imageset/icn.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/img_main_symbol.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/img_main_symbol.imageset/vote_symbol 1.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/img_main_symbol.imageset/vote_symbol 2.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/img_main_symbol.imageset/vote_symbol.png
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/img_result_character.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/img_result_character.imageset/vote_character.svg
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_background_cell.imageset/Contents.json
  24th-App-Team-1-iOS/Shared/DesignSystem/Resources/Images/Images.xcassets/Vote/vote_background_cell.imageset/image.png
Labels: ✨ FEATURE, 도현🐶

#72 feat: Kakao Login 로직 구현
  24th-App-Team-1-iOS/App/Sources/Applications/AppDelegate.swift
  24th-App-Team-1-iOS/App/Sources/Applications/SceneDelegate.swift
  24th-App-Team-1-iOS/Shared/ThirdPartyLib/Project.swift
  24th-App-Team-1-iOS/Tuist/Package.resolved
  24th-App-Team-1-iOS/Tuist/Package.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
  24th-App-Team-1-iOS/Tuist/ProjectDescriptionHelpers/TargetDependency+Templates.swift
Labels: ✨ FEATURE, 서우🐰

#68 feat: UserDefaults 설정 및 회원정보 적용
  24th-App-Team-1-iOS/Core/Storage/Sources/UserDefaultsManager.swift
  24th-App-Team-1-iOS/Core/Storage/Sources/UserDefaultsWrapper.swift
  24th-App-Team-1-iOS/Core/Storage/Sources/empty.txt
  24th-App-Team-1-iOS/Domain/LoginDomain/Sources/UserProfileEntity.swift
  24th-App-Team-1-iOS/Feature/LoginFeature/Project.swift
  24th-App-Team-1-iOS/Service/LoginService/Project.swift
  24th-App-Team-1-iOS/Service/LoginService/Sources/UserProfileResponseDTO.swift
Labels: ✨ FEATURE, 서우🐰
